### ISSUE TITLE
Historique de notre empreinte individuelle

### ISSUE THREAD

**Issue by Emmanuel-L** [FredJul/Warmd#1]
C'est un super boulot Frédéric.
Je propose d'ajouter un historique de nos évaluations afin de pouvoir déterminer notre trajectoire individuelle d'empreinte carbone à comparer vis-à-vis des objectifs de la COP21 (et des suivantes).
PS: je suis nouveau sur GitHub, aussi n'hésite pas à recadrer si besoin (langue des messages, formalisme des suggestions et problèmes).

**Comment by FredJul** [comment]
J'ai rajouté un bouton de partage dans la dernière version (disponible dans quelques jours). Cela devrait permettre de garder l'historique dans l'application de son choix. Le détail du partage n'est pour l'instant pas très complet ni joli, mais c'est un début.

Je clos donc cette tache pour l'instant, sauf si cela ne convient finalement pas.
