### ISSUE TITLE
Titre erroné

### ISSUE THREAD

**Issue by edern-appere** [FredJul/Warmd#14]
Bonjour,

Dans la partie Conseils, la rubrique concernant l'eau est intitulée "Biens et services" à la place d'eau... Le texte correspond bien à l'eau. La rubrique "Biens et services" se trouve, elle, deux paragraphes plus bas. 
Certains titres et textes sur cette même page s'affichent en anglais ("Politics") et d'autres en français.
V 1.2.0.18 sur LineageOs 17.1

Bonne continuation pour développer cette belle app !

**Comment by FredJul** [comment]
Bonjour,

En ce qui concerne les traductions manquantes c'est effectivement quelque chose que j'ai laissé passé et il y a déjà une mise à jour en cours pour corriger ça.

Pour ce qui est du titre du conseils, j'affiche pour l'instant le nom de la catégorie, et il peut y avoir plusieurs conseils dans chacune des catégories. J'imagine qu'il serait plus parlant de mettre vraiment un nom différent sur chaque conseil. Je vais regarder ça.

Merci en tout cas pour vos encouragements ! J'espère que cette nouvelle version vous plait.

**Comment by edern-appere** [comment]
Pour les conseils, je me suis permis de faire une remontée de bug car le texte parlait clairement de la consommation d'eau (prendre des douches à la place des bains, etc.) mais avec le titre Biens et services.
 
La nouvelle version est très belle, le nouveau design est très esthétique. Par contre, l'icône de l'appli n'est pas très compréhensible quand elle est affichée en petit (beaucoup moins que la précédente en tous les cas).

Une dernière petite remarque concernant l'ecran bilan. Il me semble (à tester) qu'il serait plus logique d'afficher le camembert juste en dessous du chiffre total de co2 et les boutons en dessous. J'aurai d'ailleurs plutôt placé côte à côte les liens "Voir ce que vous devez faire" et " Voir ce qui se passera si vous ne faites rien", tandis que le lien "Refaire le questionnaire" peut prendre place en bas de l'écran.

**Comment by FredJul** [comment]
Merci beaucoup pour ces retours, je pense les avoir presque tous pris en compte dans la nouvelle version (qui arrivera d'ici quelques heures / jours).

En ce qui concerne certains placements de bouton, j'attends les retours du designer qui a fait le nouveau design de l'app.
