### ISSUE TITLE
Proposer une option pour désactiver le fullscreen

### ISSUE THREAD

**Issue by edern-appere** [FredJul/Warmd#15]
Bonjour,

Sur la version 1.2.0.18 l'appli s'affiche directement en mode fullscreen. Il serait intéressant de proposer une option pour laisser le choix d'afficher l'appli en fullscreen ou non (c'est plus compliqué en mode fullscreen de retourner à l'écran d'accueil d'Android et c'est déroutant pour certaines personnes).

Bonne continuation

**Comment by FredJul** [comment]
Bonjour,

Merci beaucoup pour ce retour. Normalement la barre de status du haut est cachée (j'ai fait ceci pour des raisons esthétiques), mais la barre du bas reste normalement visible, avec donc la possibilité de retourner facilement à l'écran d'accueil. Je vais retester ça sur différente version d'android, si vous pouviez me donner la votre ça pourrait m'aider.

**Comment by edern-appere** [comment]
Autant pour moi, effectivement la barre du bas apparait bien. Désolé !
Je pense qu'on peut clôturer le bug.
