### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by RAMAR-RAR** [FredJul/Warmd#37]
The app can't be translated freely by Crowdin

**Comment by FredJul** [comment]
Could you explain a bit more what is your issue? I believe everyone can create a Crowdin account and some people already started to translate the app, so I'm not sure to understand your point

**Comment by RAMAR-RAR** [comment]
1.
1.1 I connect to the link in the README(this one:https://frju.crowdin.com/warmd)
1.2 I opened the page project
1.3 I've selected the language that I want translate
1.4 I click on translate button
1.5 Open a page of login with your nickname and crowdin domain(Nick: Frju / Domain: frju.crowdin.com)
1.6 I select to login with my credentials(selecting translator account type) because I doesn't have your crowdin credentials 
1.7. After logged appear a page with a phrase that is "Project does not exist or access to this project is limited."

2.
2.1 If I search the project on Crowdin doesn't appear

**Comment by FredJul** [comment]
Ok, I'm not completely sure but I believe I understand the problem.

I actually use the enterprise version of crowdin (which is kindly provided for free by crowdin), and the "Frju" name is not my login, but the organisation name. That means you need to create a new account on frju.crowdin.com and existing crowdin.com account will not work. However you can create the new frju.crowdin.com account with the same login/password if you want to.

I'll try to clarify the README.

**Comment by RAMAR-RAR** [comment]
I was able to translate the project, this is how i "resolved" the problem:
1. Go to the link(https://frju.crowdin.com/warmd)
2. Select the language that I want translate
4. Click on translate button
5. Open a page of login with account/organization frju.crowdin.com(don't click to choose an other account)

6.1. Go to click sign up button that is on top right of the page
6.1.1 Create the enterprise account of frju.crowdin.com
---
6.2 If already have an enterprise account of frju.crowdin.com login with credentials

**Comment by FredJul** [comment]
@RAMAR-RAR thank you a lot for you help! I think I'll publish a new version mid-march and include your translation.

Please note that if you want you can also help by providing me some links to help people reduce their footprint in Italy. These links are visible in the advices screen and I currently only provide some for France. I do not intent to be exhaustive, but would like to provide the popular ones.

As an example, for France I currently have:

Food:
    'OpenFoodFact scanner': 'https://fr.openfoodfacts.org/application-mobile-open-food-facts',
    'Karbon scanner': 'https://www.karbon.earth/',
    'TooGoodToGo Anti-Gaspi': 'https://toogoodtogo.fr/',
    'Phenix Anti-Gaspi': 'https://phenixapp.page.link/open-app',
    'Etiquettable': 'https://etiquettable.eco2initiative.com/application/',
    'Le Guide du Tri': 'https://www.consignesdetri.fr',

Material goods:
          'BackMarket : produits reconditionnés': 'https://www.backmarket.fr/',
          'LeBonCoin : petites annonces': 'https://www.leboncoin.fr/',
          'Vinted : achats de seconde main': 'https://www.vinted.fr/',
          "Geev : dons d'objets": 'https://www.geev.com/fr',
          "Emmaüs : dons/achats d'occasions": 'https://www.label-emmaus.co/fr/nos-boutiques/',
          "Zack : revend/répare/recycle l'électronique": 'https://www.zack.eco/',
          'Murphy : réparation électroménager': 'https://murfy.fr/',
          "Bricolib : location d'outils": 'https://www.bricolib.net/',
          'Le Guide du Tri': 'https://www.consignesdetri.fr',

Savings:
          'Calculateur Rift': 'https://riftapp.fr/',
          'Banque mobile Helios': 'https://www.helios.do/',

Water:
          "Douchette à réduction d'eau Hansgrohe":
              'https://www.hansgrohe.fr/articledetail-crometta-douchette-a-main-vario-green-6l-min-26336400',
          "Mousseurs robinet à réduction d'eau Hansgrohe":
              'https://www.hansgrohe.fr/articledetail-2-mousseurs-ecosmart-lavabo-et-bidet-sous-blister-13958002',
