### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by Emmanuel-L** [FredJul/Warmd#4]
Si tu as besoin de traducteur, je peux contribuer sur l'anglais et en espagnol (avec l'aide de personne dont c'est la langue maternelle).

**Comment by FredJul** [comment]
Bonjour,

Désolé pour la réponse très tardive, j'ai été bien occupé récemment par un autre projet. En ce qui concerne les traductions, Warmd est open sources et les fichiers de traductions sont visible ici: https://github.com/FredJul/Warmd/tree/master/res/string

Il est donc parfaitement possible de me proposer des modifications ou de nouvelles traductions, soit en faisant des Pull Requests soit en m'envoyant directement les fichiers.
