### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [FredJul/Warmd#44]
```
You may need to restart any open editors for them to read new settings.
+ sed -i 's/.*in_app_review.*//' pubspec.yaml
+ git apply ./fdroid.patch
error: patch failed: lib/score/about_screen.dart:1
error: lib/score/about_screen.dart: patch does not apply
```

Could you please take a look? Thanks!

**Comment by FredJul** [comment]
Hi,

Sorry for this issue, I have fixed the fdroid script and tagged a new version, this should be better now!

However I wonder if the build will succeed anyway since it is now needed to build with the "--no-sound-null-safety" option:
Example: "flutter build apk --no-sound-null-safety"

**Comment by linsui** [comment]
I'll add that, thanks!
