### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by stevenyee99** [FredJul/Warmd#5]
Hi Frederic,

My name is Steven and I've built/am building an webpage that tries to do the same thing as Warmd (footprint-finder.com).
I just want to say I think its really awesome that you did this!
Your app is pretty slick.  Love the animations and layout.  I'm excited to poke around your code and see some of your calculations!

Steven

**Comment by FredJul** [comment]
Thanks a lot for this comment!
I took most of my numbers from https://coolclimate.org/calculator, so I encourage you to look at this website since it could inspire you.
