### ISSUE TITLE
Availiability on F-droid?(just need to ask them build this)

### ISSUE THREAD

**Issue by Oymate** [FredJul/Warmd#9]

**Comment by edern-appere** [comment]
It would be great to have the app available on F-Droid ! It would be well deserved.

**Comment by FredJul** [comment]
Sorry for the late answer, but please notice that I would totally be OK with an FDroid integration. I just don't know how to do it and to be honest that not my priority right now.

So if someone knows how to do it (or just want to try) any help would be welcomed!

**Comment by Oymate** [comment]
So, last point is your flutter version and the build scripts flutter version the same? The build server is missing it.

**Comment by FredJul** [comment]
Hum, I'm not sure to understand your point. Warmd compiles with the last Flutter stable release (at the moment: 1.22.6). But in Flutter projects there is unfortunately no file to define the Flutter version (unless you use fvm).

Do you have more information about what's missing?

**Comment by Oymate** [comment]
As far as I understood the exact flutter version is needed in the srclib, Link: https://gitlab.com/fdroid/rfp/-/issues/1564#note_476985279

**Comment by Oymate** [comment]
NVM, it seems like it's actually managed by them, the app should be on F-droid now :-) https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8262/diffs#649ad87e46d7a11eeadae9c5832af3def09406fe_0_22

**Comment by FredJul** [comment]
Great! Thanks a lot for your help!

Do you know if it will be automatically updated? (I just published the v1.4.0 version)

**Comment by linsui** [comment]
> Do you know if it will be automatically updated? (I just published the v1.4.0 version)

It will be automatically updated if the MR is merged. There is a stopper now. See https://gitlab.com/fdroid/rfp/-/issues/1564#note_498052617 .

**Comment by FredJul** [comment]
oh, I actually didn't thought of that "play store" issue... I'll discuss on their gitlab to find a solution.

**Comment by FredJul** [comment]
It's now live on fdroid: https://f-droid.org/fr/packages/net.frju.verdure/

So I guess we can close that issue :)
Thanks @Oymate for your help
